programs:
  failfast:
    cmd: "./scripts/fast-fail.sh"
    args: []
    numprocs: 1
    autorestart: "never"
    exitcodes: [0]
    startretries: 1
    starttime: 3     # seconds
    stoptime: 2
    stopsignal: TERM
