programs:
  example_program:
    cmd: "echo Hello, World!"
    numprocs: 1
    autostart: true
    autorestart: "always"
    startretries: 3
    starttime: 1
    stopsignal: "TERM"
    stoptime: 5
    exitcodes: 0
    stdout: "logs/example_program.out"
    stderr: "logs/example_program.err"
    env:
      ENV_VAR: "value"
