programs:
  myapp:
    cmd: "./start.sh"
    numprocs: 1
    autostart: true
    autorestart: "always"
    exitcodes: [0]
    startretries: 3
    starttime: 1
    stopsignal: "TERM"
    stoptime: 5
    workingdir: "scripts/workingdir"
