programs:
  retry_test:
    cmd: "./scripts/fast-fail.sh"
    args: []
    numprocs: 1
    autostart: true
    autorestart: "always"       # or "unexpected"
    exitcodes: [0]
    startretries: 3             # allow exactly 3 startup retries
    starttime: 0                # no grace period; every exit is “early”
    stopsignal: "TERM"
    stoptime: 1
