programs:
  myapp:
    cmd: "echo"
    args:
      - "Hello, "
      - "World!"
    numprocs: 1
    autostart: true
    autorestart: "always"
    exitcodes: [0]
    startretries: 3
    starttime: 1
    stopsignal: "TERM"
    stoptime: 5
    stdout: "logs/myapp.out"
    stderr: "logs/myapp.err"
