programs:
  example_program:
    cmd: "echo"
    args:
      - "Hello, "
      - "World!"
    numprocs: 2
    autostart: true
    autorestart: "always"
    startretries: 3
    starttime: 1
    stopsignal: "TERM"
    stoptime: 5
    exitcodes: 0
    stdout: "logs/example_program.out"
    stderr: "logs/example_program.err"
    env:
      ENV_VAR: "value"
  example_program_2:
    cmd: "echo"
    args:
      - "Hello, "
      - "World2!"
    numprocs: 1
    autostart: false
    autorestart: "always"
    startretries: 3
    starttime: 1
    stopsignal: "TERM"
    stoptime: 5
    exitcodes: 0
    stdout: "logs/example_program.out"
    stderr: "logs/example_program.err"
    env:
      ENV_VAR: "value"
  nginx_program:
    cmd: "/opt/homebrew/bin/nginx"
    autostart: true
    autorestart: "always"
    args:
      - "-c"
      - "/opt/homebrew/etc/nginx/nginx.conf"
    exitcodes: [0, 2]
    startretries: 3
    starttime: 1
    stopsignal: "TERM"
    stoptime: 5
    numprocs: 1
  # nginx:
  #   cmd: "/opt/homebrew/bin/nginx -c /opt/homebrew/etc/nginx/nginx.conf"
  #   numprocs: 1
  #   umask: 022
  #   workingdir: /tmp
  #   autostart: false
  #   autorestart: unexpected
  #   exitcodes: [0, 2]
  #   startretries: 3
  #   starttime: 5
  #   stopsignal: TERM
  #   stoptime: 10
  #   stdout: /tmp/nginx.stdout
  #   stderr: /tmp/nginx.stderr
  #   env:
  #   STARTED_BY: taskmaster
  #   ANSWER: 42
  # vogsphere:
  #   cmd: "/usr/local/bin/vogsphere-worker --no-prefork"
  #   numprocs: 8
  #   umask: 077
  #   workingdir: /tmp
  #   autostart: true
  #   autorestart: unexpected
  #   exitcodes: 0
  #   startretries: 3
  #   starttime: 5
  #   stopsignal: USR1
  #   stoptime: 10
  #   stdout: /tmp/vgsworker.stdout
  #   stderr: /tmp/vgsworker.stderr