programs:
  env_tester:
    cmd: "./scripts/env_test.sh"
    args: []
    numprocs: 1
    autostart: true
    autorestart: "never"
    exitcodes: [0]
    startretries: 1
    starttime: 1
    stopsignal: "TERM"
    stoptime: 1
    env:
      MYVAR: "HelloWorld"      # ← this is what we want to test
