programs:
  sigtester:
    cmd: "./scripts/sigtest.sh"
    args: []
    numprocs: 1
    autostart: true
    autorestart: "never"
    exitcodes: [0]
    startretries: 1
    starttime: 1
    stopsignal: "TERM"
    stoptime: 1    # allow up to 3s for graceful shutdown
