programs:
  good_exit:
    cmd: "./scripts/exit-zero.sh"
    args: []
    numprocs: 1
    autostart: true
    startretries: 0
    starttime: 1
    stoptime: 1
    stopsignal: TERM
    autorestart: "always"
    exitcodes: [0]

  bad_exit:
    cmd: "./scripts/exit-one.sh"
    args: []
    numprocs: 1
    autostart: true
    startretries: 0
    starttime: 1
    stoptime: 1
    stopsignal: TERM
    autorestart: "unexpected"
    exitcodes: [0]

  alternate_ok_exit:
    cmd: "./scripts/exit-two.sh"
    args: []
    numprocs: 1
    autostart: true
    startretries: 0
    starttime: 1
    stoptime: 1
    stopsignal: TERM
    autorestart: "unexpected"
    exitcodes: [0, 2]
